name: CAVU Cellars
favicon: null
layout_spectrum: 1
typography_spectrum: 0.53869
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#211f20'
    - '#d3a748'
    - '#5d98d0'
    - '#1d56a7'
  brandStrength: 0.8125
  lightness: 0.5
  saturation: 0.6875
  rhythmicContrast: 0.75
purpose: []
