name: CAVU Cellars
favicon: null
layout_spectrum: 0.24194343155249953
typography_spectrum: 0.3888837802223861
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#211f20'
    - '#d3a748'
    - '#5d98d0'
    - '#1d56a7'
  brandStrength: 0.6875
  lightness: 0.5239748700987548
  saturation: 0.31639882922172546
  rhythmicContrast: 0.673722198465839
purpose: []
